version: '3.2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/
            - /config/docker/nginx:/etc/nginx/conf.d
            - ./var/log:/var/log/nginx/
        links:
            - php

    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=parking
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=pass

    php:
        build: ./config/docker/php
        volumes:
            - .:/var/www/html
        ports:
            - 9000:9000
        links:
            - db
