version: '3.2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/
            - ./config/docker/nginx:/etc/nginx/conf.d
            - ./var/log:/var/log/nginx/
        links:
            - php

    php:
        build: ./config/docker/php
        volumes:
            - .:/var/www
        ports:
            - 9000:9000
        links:
            - db

    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: $DATABASE_NAME
            POSTGRES_USER: $DATABASE_USER
            POSTGRES_PASSWORD: $DATABASE_PASSWORD
